# .github/workflows/build.yml
name: Build Design Tokens

on:
  push:
    branches:
      - master # Corrigido para 'master'
  pull_request:
    branches:
      - master # Corrigido para 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão mais recente LTS

      - name: Install dependencies
        # Se você está usando 'npm install' no seu projeto local, mantenha assim.
        # Se você está usando 'yarn install' localmente, considere usar 'yarn install' aqui,
        # mas certifique-se de que o Yarn está disponível no ambiente do Action.
        run: npm install --legacy-peer-deps

      - name: Build Style Dictionary tokens
        # *** MUDANÇA AQUI: Troque de 'yarn build:tokens' para 'npm run build:tokens' ***
        run: npm run build:tokens

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: design-tokens
          path: build/ # Caminho da pasta que contém os tokens compilados
